[package]
name = "haven-in-egor"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
haven = { package = "haven-ui", path = "../..", default-features = false, features = ["paint-anyrender"] }
anyrender_vello_hybrid = "0.10.0"
wgpu_context = "0.9.0"
rustc-hash = "2"
vello_hybrid = "0.1.0"
vello_common = "0.1.0"
wgpu = "29.0.3"
egor_app = "0.10.0"
egor_render = "0.10.0"
winit = "0.30.12"
